version: "2"
volumes:
  zeebe_data:
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    restart: always
    mem_limit: 2g

  cambpm:
    image: camunda/camunda-bpm-platform:7.11.0
    container_name: cambpm
    environment:
      - TZ=Europe/Berlin
    ports:
      - 8080:8080
    restart: always
    mem_limit: 1g

  optimize:
    image: optimize-hackweek:latest
    build: ../hackweek-docker
    container_name: optimize
    depends_on:
      - elasticsearch
      - cambpm
    ports:
      - 8091:8090
    restart: always
    mem_limit: 3g

  process-graph:
    image: process-graph-hackweek:latest
    build: ../process-graph
    container_name: process-graph
    ports:
      - 8579:8579
    restart: always

####

  kafka-connector:
    image: ingest-hackweek:latest
    build: ./kafka-connector
    container_name: kafka-connector
    restart: always
    depends_on:
      - kafka
      - optimize

####
  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: "confluentinc/cp-kafka:latest"
    hostname: kafka
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zeebe:
    image: camunda/zeebe:0.21.1
    ports:
      - "26500:26500"
      - "9600:9600"
    volumes:
      - zeebe_data:/usr/local/zeebe/data
      - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    depends_on:
      - elasticsearch

  operate:
    image: camunda/operate:1.1.0-alpha3
    ports:
      - "8088:8080"
    volumes:
      - ./application.yml:/usr/local/operate/config/application.yml
