{
 "title": "Zeebe",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(zeebe_stream_processor_events_total, namespace)"
   },
   {
    "name": "instance",
    "query": "label_values(zeebe_stream_processor_events_total{namespace=~\"$namespace\"}, instance)"
   },
   {
    "name": "partition",
    "query": "label_values(zeebe_stream_processor_events_total{namespace=~\"$namespace\", instance=~\"$instance\"}, partition)"
   }
  ]
 },
 "panels": [
  {
   "title": "Workflow Instance Events per second (range = 1m)",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\", type=\"PROCESS\"}[1m])) by (action)"
    }
   ]
  },
  {
   "title": "Job events per second (range = 1m)",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(zeebe_job_events_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\"}[1m])) by (action)",
     "legendFormat": "Stream Processor"
    }
   ]
  },
  {
   "title": "Workflow Instance Events per second (range = 1m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\", type=\"PROCESS\"}[1m])) by (action)",
     "legendFormat": "Workflow Instance ({{action}})"
    },
    {
     "expr": "sum(rate(zeebe_job_events_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\"}[1m])) by (action)",
     "legendFormat": "Job ({{action}})"
    }
   ]
  },
  {
   "title": "Running Workflow Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(zeebe_running_workflow_instances_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\"})",
     "legendFormat": "Workflow Instance"
    },
    {
     "expr": "sum(zeebe_pending_jobs_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\"})",
     "legendFormat": "Jobs"
    },
    {
     "expr": "sum(zeebe_pending_incidents_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\"})",
     "legendFormat": "Incidents"
    }
   ]
  },
  {
   "title": "Workflow Instance Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\", type=\"PROCESS\"}) by (action)",
     "legendFormat": "Workflow Instance ({{action}})"
    },
    {
     "expr": "sum(zeebe_job_events_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\"}) by (action)",
     "legendFormat": "Job ({{action}})"
    }
   ]
  }
 ]
}