{
 "title": "Zeebe",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(zeebe_stream_processor_events_total, namespace)"
   },
   {
    "name": "instance",
    "query": "label_values(zeebe_stream_processor_events_total{namespace=~\"$namespace\"}, instance)"
   },
   {
    "name": "partition",
    "query": "label_values(zeebe_stream_processor_events_total{namespace=~\"$namespace\", instance=~\"$instance\"}, partition)"
   }
  ]
 },
 "panels": [
  {
   "title": "Workflow Instance Events per second (range = 1m)",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\", type=\"PROCESS\"}[1m])) by (action)"
    }
   ]
  },
  {
   "title": "Job events per second (range = 1m)",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(zeebe_job_events_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\"}[1m])) by (action)",
     "legendFormat": "Stream Processor"
    }
   ]
  },
  {
   "title": "Workflow Instance Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\", type=\"PROCESS\"}) by (action)",
     "legendFormat": "Workflow Instance ({{action}})"
    },
    {
     "expr": "sum(zeebe_job_events_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\"}) by (action)",
     "legendFormat": "Job ({{action}})"
    }
   ]
  },
  {
   "title": "Workflow Instance Events per second (range = 1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\", type=\"PROCESS\"}[1m])) by (action)",
     "legendFormat": "Workflow Instance ({{action}})"
    },
    {
     "expr": "sum(rate(zeebe_job_events_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\"}[1m])) by (action)",
     "legendFormat": "Job ({{action}})"
    }
   ]
  },
  {
   "title": "Stream Processor Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(zeebe_stream_processor_events_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\"}) by (action, processor)",
     "legendFormat": "{{processor}} ({{action}})"
    },
    {
     "expr": "sum(zeebe_exporter_events_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\"}) by (action, processor)",
     "legendFormat": "exporter ({{action}})"
    }
   ]
  },
  {
   "title": "Stream Processor Events per second (range = 1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeebe_stream_processor_events_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\"}[1m])) by (action, processor)",
     "legendFormat": "{{processor}} ({{action}})"
    },
    {
     "expr": "sum(rate(zeebe_exporter_events_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\"}[1m])) by (action, processor)",
     "legendFormat": "exporter ({{action}})"
    }
   ]
  },
  {
   "title": "Running Workflow Instances",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(zeebe_running_workflow_instances_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\"})",
     "legendFormat": "Workflow Instance"
    },
    {
     "expr": "sum(zeebe_pending_jobs_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\"})",
     "legendFormat": "Jobs"
    },
    {
     "expr": "sum(zeebe_pending_incidents_total{namespace=~\"$namespace\",partition=~\"$partition\",instance=~\"$instance\"})",
     "legendFormat": "Incidents"
    }
   ]
  },
  {
   "title": "Stream Processor vs Exporter",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(zeebe_stream_processor_events_total{namespace=~\"$namespace\", action=~\"skipped|processed\", partition=~\"$partition\", instance=~\"$instance\"}) - sum(zeebe_exporter_events_total{namespace=~\"$namespace\", partition=~\"$partition\", instance=~\"$instance\"})",
     "legendFormat": "Events processed but not exported"
    }
   ]
  },
  {
   "title": "Processing Latency (Command)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(zeebe_stream_processor_latency_bucket{partition=~\"$partition\", recordType=\"COMMAND\"}[30s])) by (le)",
     "legendFormat": "{{le}}s"
    }
   ]
  },
  {
   "title": "Processing Latency (Event)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(zeebe_stream_processor_latency_bucket{partition=~\"$partition\", recordType=\"EVENT\"}[30s])) by (le)",
     "legendFormat": "{{le}}s"
    }
   ]
  },
  {
   "title": "Elasticsearch Exporter (Flush Duration)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(zeebe_elasticsearch_exporter_flush_duration_seconds_bucket{partition=~\"$partition\"}[30s])) by (le)",
     "legendFormat": "{{le}}s"
    }
   ]
  },
  {
   "title": "Elasticsearch Exporter (Bulk Size)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(zeebe_elasticsearch_exporter_bulk_size_bucket{partition=~\"$partition\"}[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Create Workflow Instance Latency (gRPC)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_latency_seconds_bucket{grpc_method=\"CreateWorkflowInstance\"}[30s])) by (le)",
     "legendFormat": "{{le}}s"
    }
   ]
  },
  {
   "title": "Activate Jobs Latency (gRPC)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_latency_seconds_bucket{grpc_method=\"ActivateJobs\"}[30s])) by (le)",
     "legendFormat": "{{le}}s"
    }
   ]
  },
  {
   "title": "Complete Job Latency (gRPC)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_latency_seconds_bucket{grpc_method=\"CompleteJob\"}[30s])) by (le)",
     "legendFormat": "{{le}}s"
    }
   ]
  },
  {
   "title": "gRPC requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_handled_total{namespace=~\"$namespace\", instance=~\"$instance\"}) by (grpc_method, code)",
     "legendFormat": "{{grpc_method}} ({{code}})"
    }
   ]
  },
  {
   "title": "gRPC requests per second (range = 1m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])) by (grpc_method, code)",
     "legendFormat": "{{grpc_method}} ({{code}})"
    }
   ]
  }
 ]
}