---
apiVersion: v1
kind: Service
metadata:
  name: metrics-grafana-loadbalancer
  labels:
      app: grafana
spec:
  type: LoadBalancer
  ports:
      - port: 80
        targetPort: grafana
        protocol: TCP
        name: http
  selector:
      app: grafana
